# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1 ,2 ,3 ],
                  [5, 4,8]] , np.int8)

In [3]:
myarr[1,2]

8

In [4]:
myarr.shape

(2, 3)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
arr2= np.array([[1,2], [3,4] ,[5, 7] ,[8, 9]])

In [7]:
arr2

array([[1, 2],
       [3, 4],
       [5, 7],
       [8, 9]])

In [8]:
arr3 = np.arange(20)

In [9]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
lspace = np.linspace(1 , 100 , 10)

In [11]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [12]:
emp = np.empty_like(lspace)

In [13]:
emp

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [14]:
ide = np.identity(4)

In [15]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
ide.shape

(4, 4)

In [17]:
rs = ide.reshape(2 ,8)

In [18]:
rs

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [19]:
rs1 = rs.ravel()

In [20]:
rs1.shape

(16,)

In [21]:
x = ([1,2,4],[10,21,33],[5,3,8],[9, 12, 55])

In [22]:
ar = np.array(x)

In [23]:
ar

array([[ 1,  2,  4],
       [10, 21, 33],
       [ 5,  3,  8],
       [ 9, 12, 55]])

In [24]:
#ar.sum(axis=1)
ar.sum(axis =0)

array([ 25,  38, 100])

In [25]:
art= ar.T

In [26]:
art

array([[ 1, 10,  5,  9],
       [ 2, 21,  3, 12],
       [ 4, 33,  8, 55]])

In [27]:
ar.flat

In [28]:
for item in ar.flat:
    print(item)

1
2
4
10
21
33
5
3
8
9
12
55


In [29]:
ar.argmax()

11

In [30]:
ar.argmin()

0

In [31]:
ar.argmax(axis=0)

array([1, 1, 3], dtype=int64)

In [32]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [33]:
np.where(ar>3)

(array([0, 1, 1, 1, 2, 2, 3, 3, 3], dtype=int64),
 array([2, 0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [34]:
np.count_nonzero(ar)

12

In [35]:
res = ar.tolist()
res
type(ar.tolist())

list

In [36]:
ar[0:9:1]

array([[ 1,  2,  4],
       [10, 21, 33],
       [ 5,  3,  8],
       [ 9, 12, 55]])

In [37]:
ar

array([[ 1,  2,  4],
       [10, 21, 33],
       [ 5,  3,  8],
       [ 9, 12, 55]])

# Slicing

**array_name[starting index : last-1 index : step to jump]**

In [38]:
arr1 = np.array([1 ,2, 3, 4, 5, 88,7 , 8, 89, 9, 100,])

In [39]:
arr1[3:10:2]

array([ 4, 88,  8,  9])

In [40]:
arr1[1::1] # this will print array till last by just taking step in consideration

array([  2,   3,   4,   5,  88,   7,   8,  89,   9, 100])

In [41]:
arr1[::3]

array([1, 4, 7, 9])

In [42]:
arr1[:]

array([  1,   2,   3,   4,   5,  88,   7,   8,  89,   9, 100])

In [43]:
ar

array([[ 1,  2,  4],
       [10, 21, 33],
       [ 5,  3,  8],
       [ 9, 12, 55]])

In [44]:
ar[2:-1, 2:] #ar[column_start:column_end , row_start:row_end]

array([[8]])

In [45]:
arr4 = np.ndarray(shape=(7) , dtype=int)

In [46]:
arr4

array([4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 5242972])

In [47]:
arr4.shape

(7,)

In [48]:
arr4.ndim

1

In [49]:
arr4.size

7

In [50]:
n = arr4.size
print("Enter the %d numbers in array :")
for i in range(n):
    print(i+1)
    arr4[i] = int(input(":"))

Enter the %d numbers in array :
1
:4
2
:5
3
:7
4
:8
5
:9
6
:10
7
:11


In [51]:
arr4

array([ 4,  5,  7,  8,  9, 10, 11])

In [52]:
arr4.reshape(7,1)

array([[ 4],
       [ 5],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])